### ISSUE TITLE
Ticker du Shield

### ISSUE THREAD

**Issue by Folders** [Folders/Submarine_Module#11]
J'ai du désactiver pour l'ESP "d1_mini" la librairie suivante "sstaub/Ticker@^4.4.0"

Cette librairie remplace la libraire ticker de base, et n'as pas les mêmes appel. Du coup, c'est impossible d'utiliser les tickers de base!

Il faut : 
1. Supprimer la librairie "sstaub/Ticker@^4.4.0" dans le fichier .ini
2. Remplacer tout les tickers par celui de base dans le projet Shield

**Comment by danansermin** [comment]
Résolue pour le shield
